name: 'Download IPFS Distribution'
description: 'Download executable from dist.ipfs.io'
inputs:
  name:
    description: 'Name of the distribution to download'
    required: true
    default: 'go-ipfs'
  version:
    description: 'Version of the distribution to download(defaults to latest stable version)'
    required: false
  working-directory:
    description: "Directory where the action is going to be performed(defaults to temp directory)"
    required: false
  install-directory:
    description: "Directory where the executable is going to be copied(defaults to /usr/local/bin or /usr/bin on windows)"
    required: false
  cache:
    description: "A boolean value to indicate the archive cache should be used"
    required: true
    default: 'true'
outputs:
  executable:
    description: "The name of the executable"
  executables:
    description: "The names of all the executables"
  cache-hit:
    description: "A boolean value to indicate the archive was downloaded from cache"
runs:
  using: 'node16'
  main: 'index.js'
