name: Test
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        name: [go-ipfs]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: download-ipfs-distribution-action
      - id: distribution
        uses: ./download-ipfs-distribution-action
        with:
          name: ${{ matrix.name }}
      - run: ${{ steps.distribution.outputs.executable }} --help
        shell: bash
