name: Test
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        name: [go-ipfs]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: download-ipfs-distribution-action
      - id: distribution
        uses: ./download-ipfs-distribution-action
        with:
          name: ${{ matrix.name }}
          cache: false
      # ipget for linux-amd64 requires GLIBC_2.32 but GLIBC_2.31 is installed
      - if: ${{ matrix.os != 'ubuntu-latest' || matrix.name != 'ipget' }}
        run: ${{ steps.distribution.outputs.executable }} --help
        shell: bash
