name: Test Cache
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: download-ipfs-distribution-action
      - uses: ./download-ipfs-distribution-action
  Use-Action-Again:
    needs: [Use-Action]
    name: Use Action Again
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: download-ipfs-distribution-action
      - if: runner.os != 'Windows'
        run: echo '127.0.0.1 dist.ipfs.tech' | sudo tee -a /etc/hosts
        shell: bash
      - if: runner.os == 'Windows'
        run: echo '127.0.0.1 dist.ipfs.tech' | tee -a C:/windows/system32/drivers/etc/hosts
        shell: bash
      - id: distribution
        uses: ./download-ipfs-distribution-action
      - if: ${{ steps.distribution.outputs.cache-hit != 'true' }}
        run: exit 1
        shell: bash
