name: Test Cache Download
on: [push]
jobs:
  Wait-For-Cache-Upload:
    name: Wait for Cache Upload
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Cache Upload
        uses: lewagon/wait-on-check-action@e2558238c09778af25867eb5de5a3ce4bbae3dcd # v1.1.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          check-regexp: 'Cache Upload \(.*\)'
          allowed-conclusions: success
  Cache-Download:
    name: Cache Download
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          path: download-ipfs-distribution-action
      - if: runner.os != 'Windows'
        run: echo '127.0.0.1 dist.ipfs.tech' | sudo tee -a /etc/hosts
        shell: bash
      - if: runner.os == 'Windows'
        run: echo '127.0.0.1 dist.ipfs.tech' | tee -a C:/windows/system32/drivers/etc/hosts
        shell: bash
      - id: distribution
        uses: ./download-ipfs-distribution-action
      - if: ${{ steps.distribution.outputs.cache-hit != 'true' }}
        run: exit 1
        shell: bash
