name: Test
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        name: [go-ipfs]
    steps:
      - uses: actions/checkout@v2
        with:
          path: download-ipfs-distribution-action
      - uses: ./download-ipfs-distribution-action
        with:
          name: ${{ matrix.name }}
